name: '[ Development ] ECR Deploy'

on: 
  push:
    branches:
      - development
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  Deploy-ECR:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: ECR Deploy
        uses: ./.github/actions/deploy
        with:
          env: dev
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_repo_name: ecr-dev
